In [1]:
import pandas as pd
import numpy as np

import joblib

from sklearn.model_selection import train_test_split, cross_validate, StratifiedKFold
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
df_2 = pd.read_excel("D:\Multi Disease Model\Data\Diabetes_Data.xlsx")
df_2 = df_2.drop_duplicates()
df_2.columns = df_2.columns.str.strip()

In [3]:
df_2.head()

,Age,Gender,BMI,BloodPressure,Glucose,HbA1c,Insulin,PhysicalActivity,FamilyHistory,Smoking,Diabetes
0,58,Male,18.6,125,132,6.1,72,High,Yes,No,No
1,20,Male,20.1,119,199,8.7,121,High,No,Yes,No
2,46,Female,35.8,90,110,9.4,194,Medium,Yes,Yes,Yes
3,79,Female,20.2,138,94,7.0,196,High,No,Yes,No
4,64,Female,29.8,138,90,8.4,205,High,Yes,Yes,Yes

In [4]:
X = df_2.drop("Diabetes", axis=1)
y = df_2["Diabetes"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [5]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [6]:
cat_cols = ["Gender","PhysicalActivity","FamilyHistory","Smoking"]
num_cols = ["Age","BMI","BloodPressure","Glucose","HbA1c","Insulin"]

In [7]:
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(sparse_output=False,handle_unknown="ignore"))
])

In [8]:
preprocessor = ColumnTransformer([
    ('num', numerical_pipeline, num_cols),
    ('cat', categorical_pipeline, cat_cols)
])

In [9]:
model_logistic = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(random_state=42))
])
model_knn = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', KNeighborsClassifier(n_neighbors=5))
])
model_svc = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', SVC(random_state=42))
])
model_decision_tree = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(random_state=42))
])
model_random_forest = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])
model_gradient_boosting = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', GradientBoostingClassifier(random_state=42))
])

In [10]:
cv = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

scores_log_reg = cross_validate(
    model_logistic,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)


Accuracy_log_reg = scores_log_reg["test_accuracy"].mean()
Precision_log_reg =scores_log_reg["test_precision"].mean()
Recall_log_reg = scores_log_reg["test_recall"].mean()
F1_log_reg = scores_log_reg["test_f1"].mean()


scores_knn = cross_validate(
    model_knn,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)

Accuracy_knn = scores_knn["test_accuracy"].mean()
Precision_knn =scores_knn["test_precision"].mean()
Recall_knn = scores_knn["test_recall"].mean()
F1_knn = scores_knn["test_f1"].mean()


scores_svc = cross_validate(
    model_svc,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)

Accuracy_svc = scores_svc["test_accuracy"].mean()
Precision_svc =scores_svc["test_precision"].mean()
Recall_svc = scores_svc["test_recall"].mean()
F1_svc = scores_svc["test_f1"].mean()


scores_dec_tree = cross_validate(
    model_decision_tree,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)

Accuracy_dec_tree = scores_dec_tree["test_accuracy"].mean()
Precision_dec_tree =scores_dec_tree["test_precision"].mean()
Recall_dec_tree = scores_dec_tree["test_recall"].mean()
F1_dec_tree = scores_dec_tree["test_f1"].mean()


scores_rand_forest = cross_validate(
    model_random_forest,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)

Accuracy_rand_forest = scores_rand_forest["test_accuracy"].mean()
Precision_rand_forest =scores_rand_forest["test_precision"].mean()
Recall_rand_forest = scores_rand_forest["test_recall"].mean()
F1_rand_forest = scores_rand_forest["test_f1"].mean()


scores_grad_boost = cross_validate(
    model_gradient_boosting,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)

Accuracy_grad_boost = scores_grad_boost["test_accuracy"].mean()
Precision_grad_boost =scores_grad_boost["test_precision"].mean()
Recall_grad_boost = scores_grad_boost["test_recall"].mean()
F1_grad_boost = scores_grad_boost["test_f1"].mean()

In [11]:
cv_df = pd.DataFrame({
    "Model":["Log Reg","KNN","SVM","Dec Tree","Rand_Forest","Grad Boost"],
    "Accuracy":[Accuracy_log_reg,Accuracy_knn,Accuracy_svc,Accuracy_dec_tree,Accuracy_rand_forest,Accuracy_grad_boost],
    "Precision":[Precision_log_reg,Precision_knn,Precision_svc,Precision_dec_tree,Precision_rand_forest,Precision_grad_boost],
    "Recall":[Recall_log_reg,Recall_knn,Recall_svc,Recall_dec_tree,Recall_rand_forest,Recall_grad_boost],
    "F1":[F1_log_reg,F1_knn,F1_svc,F1_dec_tree,F1_rand_forest,F1_grad_boost]
})

cv_df

         Model  Accuracy  Precision    Recall        F1
0      Log Reg    0.8675   0.866284  0.901111  0.883011
1          KNN    0.8000   0.813946  0.833333  0.823154
2          SVM    0.8675   0.876038  0.887475  0.881349
3     Dec Tree    0.8125   0.842328  0.819293  0.828844
4  Rand_Forest    0.8625   0.859702  0.901212  0.878408
5   Grad Boost    0.9000   0.911386  0.909899  0.910223

In [12]:
model_gradient_boosting.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'BMI',
                                                   'BloodPressure', 'Glucose',
                                                   'HbA1c', 'Insulin']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Gender', 'PhysicalActivity',
                                                   'FamilyHistory',
                                                   'Smoking'])])),
                ('classifier', GradientBoostingClassifier(random_state=42))])

In [13]:
preds = model_gradient_boosting.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, preds))
print("Test Precision:", precision_score(y_test, preds))
print("Test Recall:", recall_score(y_test, preds))
print("Test F1 Score:", f1_score(y_test, preds))

Test Accuracy: 0.92
Test Precision: 0.9130434782608695
Test Recall: 0.9130434782608695
Test F1 Score: 0.9130434782608695

In [15]:
joblib.dump(model_gradient_boosting, "D:\Multi Disease Model\Models\model_diabetes.pkl")

['D:\\Multi Disease Model\\Models\\model_diabetes.pkl']